# Generated by Django 3.2.6 on 2021-08-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='cust',
        ),
    ]
